# Generated by Django 4.0.6 on 2022-08-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asd',
            new_name='Articles',
        ),
    ]
