# Generated by Django 4.0.6 on 2022-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
